### ISSUE TITLE
GLN_HIP chemical perception fails

### ISSUE THREAD

**Issue by j-wags** [openforcefield/amber-ff-porting#26]
(off-dev) jeffreywagner@JW-MBP$ python test_parameterize_tripeptides.py

MainChain/GLN_HIP/GLN_HIP
HarmonicBondForce 6.00869083404541 kJ/mol
HarmonicAngleForce 101.89446258544922 kJ/mol
PeriodicTorsionForce 134.29551696777344 kJ/mol
NonbondedForce -252.6314697265625 kJ/mol
-10.43280029296875 kJ/mol
[H]C1=C(N(C(=[N+]1[H])[H])[H])C([H])([H])[C@@]([H])(C(=O)N([H])C([H])([H])[H])N([H])C(=O)[C@]([H])(C([H])([H])C([H])([H])C(=O)N([H])[H])N([H])C(=O)C([H])([H])[H]
Traceback (most recent call last):
  File "test_parameterize_tripeptides.py", line 100, in <module>
    off_sys = ff.create_openmm_system(mol.to_topology(),)#allow_nonintegral_charges=True)
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 1293, in create_openmm_system
    parameter_handler.create_force(system, topology, **kwargs)
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 2520, in create_force
    exception_cls=UnassignedAngleParameterException,
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 2197, in _check_all_valence_terms_assigned
    raise exception
openforcefield.typing.engines.smirnoff.parameters.UnassignedAngleParameterException: AngleHandler was not able to find parameters for the following valence terms:

- Topology indices (33, 35, 36): names and elements ( C), ( N), ( H), 
- Topology indices (36, 35, 37): names and elements ( H), ( N), ( C),

**Comment by j-wags** [comment]
It's the CNH angles about this atom. My first guess is that it's an aromaticity perception problem. I'll look into that possibility first.  

<img width="517" alt="Screen Shot 2020-09-01 at 5 06 06 PM" src="https://user-images.githubusercontent.com/16329175/91917747-a9a96080-ec75-11ea-9a87-6100de2148f8.png">

**Comment by j-wags** [comment]
Second guess is that it's something to do with HIP being a superstructure of HID/HIE, and that this can be solved with a parameter-precedence change.

**Comment by j-wags** [comment]
Hm, looking at ALA_HIP shows a different pattern of double bonds on the sidechain. So it's possible that the charge moved. Yuck. 

I need to figure out which structure was used for the _training_, and whether pymol is guessing at the double bonds or if they're explicit.

<img width="570" alt="Screen Shot 2020-09-01 at 5 34 33 PM" src="https://user-images.githubusercontent.com/16329175/91919023-7d8fde80-ec79-11ea-9618-dcbe4938d9f9.png">

**Comment by j-wags** [comment]
The double bonds seem to be explicit.

**Comment by j-wags** [comment]
I suspect that this is a difference between the particular kekule structure in the dipeptide structure (which was used to make the FF/SMARTS) and the many kekule structures in the tripeptides involving HIS/HIE/HID/HIP. I could probably use a similar mechanism as #29 to fix this.
