### ISSUE TITLE
LYN_ARG chemical perception fails

### ISSUE THREAD

**Issue by j-wags** [openforcefield/amber-ff-porting#27]
Judging by the failing indices, it seems like something wrong with all of the ARG residue. Comparing to ALA_ARG, I see that the guanidinium double bond has moved. 

```
(off-dev) jeffreywagner@JW-MBP$ python test_parameterize_tripeptides.py


MainChain/LYN_ARG/LYN_ARG
HarmonicBondForce 9.76828670501709 kJ/mol
HarmonicAngleForce 8.674139022827148 kJ/mol
PeriodicTorsionForce 75.72264099121094 kJ/mol
NonbondedForce -720.9594116210938 kJ/mol
-626.7942504882812 kJ/mol
[H][C@@](C(=O)N([H])[C@]([H])(C(=O)N([H])C([H])([H])[H])C([H])([H])C([H])([H])C([H])([H])N([H])C(=[N+]([H])[H])N([H])[H])(C([H])([H])C([H])([H])C([H])([H])C([H])([H])N([H])[H])N([H])C(=O)C([H])([H])[H]
Traceback (most recent call last):
  File "test_parameterize_tripeptides.py", line 101, in <module>
    off_sys = ff.create_openmm_system(mol.to_topology(),)#allow_nonintegral_charges=True)
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/forcefield.py", line 1293, in create_openmm_system
    parameter_handler.create_force(system, topology, **kwargs)
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 2520, in create_force
    exception_cls=UnassignedAngleParameterException,
  File "/Users/jeffreywagner/projects/OpenForceField/openforcefield/openforcefield/typing/engines/smirnoff/parameters.py", line 2197, in _check_all_valence_terms_assigned
    raise exception
openforcefield.typing.engines.smirnoff.parameters.UnassignedAngleParameterException: AngleHandler was not able to find parameters for the following valence terms:

- Topology indices (49, 51, 53): names and elements ( C), ( N), ( C), 
- Topology indices (40, 42, 46): names and elements ( N), ( C), ( N), 
- Topology indices (35, 34, 37): names and elements ( H), ( C), ( C), 
- Topology indices (37, 40, 41): names and elements ( C), ( N), ( H), 
- Topology indices (32, 31, 34): names and elements ( H), ( C), ( C), 
- Topology indices (28, 27, 29): names and elements ( H), ( N), ( C), 
- Topology indices (47, 46, 48): names and elements ( H), ( N), ( H), 
- Topology indices (33, 31, 34): names and elements ( H), ( C), ( C), 
- Topology indices (39, 37, 40): names and elements ( H), ( C), ( N), 
- Topology indices (29, 31, 34): names and elements ( C), ( C), ( C), 
- Topology indices (32, 31, 33): names and elements ( H), ( C), ( H), 
- Topology indices (29, 31, 33): names and elements ( C), ( C), ( H), 
- Topology indices (29, 31, 32): names and elements ( C), ( C), ( H), 
- Topology indices (34, 37, 40): names and elements ( C), ( C), ( N), 
- Topology indices (36, 34, 37): names and elements ( H), ( C), ( C), 
- Topology indices (30, 29, 31): names and elements ( H), ( C), ( C), 
- Topology indices (38, 37, 40): names and elements ( H), ( C), ( N), 
- Topology indices (31, 34, 36): names and elements ( C), ( C), ( H), 
- Topology indices (43, 42, 46): names and elements ( N), ( C), ( N), 
- Topology indices (31, 34, 37): names and elements ( C), ( C), ( C), 
- Topology indices (42, 46, 47): names and elements ( C), ( N), ( H), 
- Topology indices (29, 49, 50): names and elements ( C), ( C), ( O), 
- Topology indices (34, 37, 39): names and elements ( C), ( C), ( H), 
- Topology indices (27, 29, 49): names and elements ( N), ( C), ( C), 
- Topology indices (38, 37, 39): names and elements ( H), ( C), ( H), 
- Topology indices (42, 46, 48): names and elements ( C), ( N), ( H), 
- Topology indices (31, 34, 35): names and elements ( C), ( C), ( H), 
- Topology indices (31, 29, 49): names and elements ( C), ( C), ( C), 
- Topology indices (40, 42, 43): names and elements ( N), ( C), ( N), 
- Topology indices (37, 40, 42): names and elements ( C), ( N), ( C), 
- Topology indices (41, 40, 42): names and elements ( H), ( N), ( C), 
- Topology indices (42, 43, 44): names and elements ( C), ( N), ( H), 
- Topology indices (34, 37, 38): names and elements ( C), ( C), ( H), 
- Topology indices (27, 29, 31): names and elements ( N), ( C), ( C), 
- Topology indices (42, 43, 45): names and elements ( C), ( N), ( H), 
- Topology indices (30, 29, 49): names and elements ( H), ( C), ( C), 
- Topology indices (35, 34, 36): names and elements ( H), ( C), ( H), 
- Topology indices (27, 29, 30): names and elements ( N), ( C), ( H), 
- Topology indices (44, 43, 45): names and elements ( H), ( N), ( H), 
```
LYN_ARG
<img width="546" alt="Screen Shot 2020-09-01 at 5 16 33 PM" src="https://user-images.githubusercontent.com/16329175/91918159-ea55a980-ec76-11ea-910b-4605146d9d8f.png">

ALA_ARG
<img width="551" alt="Screen Shot 2020-09-01 at 5 17 31 PM" src="https://user-images.githubusercontent.com/16329175/91918201-1f61fc00-ec77-11ea-91f8-f17a4d5af215.png">

**Comment by j-wags** [comment]
I've checked all other XXX_ARG structures, and only LYN_ARG has this bonding pattern.
